var myGymExercise = "Dumbbell uthao or lagao"

for(let a = 1; a < 13; a++) {
  console.log(myGymExercise)
}

var workoutDays = {
    monday:"M Chest",
    tuesday:"T wings",
    wednesday:"W shoulder",
    thursday:"T biceps",
    friday:"F triceps",
    saturday:"S legs + forearms",
}

// loops 
for (a = 0; a <= 5; a++){
    console.log(workoutDays.monday,workoutDays.tuesday,workoutDays.wednesday,workoutDays.thursday,workoutDays.friday,workoutDays.saturday)
}